service: todos-backend

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  region: ap-southeast-1
  stage: ${opt:stage, 'dev'}

functions:
  hello:
    handler: src/functions/hello/main.handler
    events:
      - http:
          path: /hello
          method: get
          cors: true
  createTodo:
    handler: src/functions/createTodo/main.handler
    events:
      - http:
          path: /todos
          method: post
          cors: true
  deleteTodo:
    handler: src/functions/deleteTodo/main.handler
    events:
      - http:
          path: /todos/{id}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                id: true

plugins:
  - serverless-plugin-typescript
